/*
 * This file is generated by jOOQ.
 */
package net.johanbasson.datavault.support.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import net.johanbasson.datavault.support.jooq.Indexes;
import net.johanbasson.datavault.support.jooq.Keys;
import net.johanbasson.datavault.support.jooq.Public;
import net.johanbasson.datavault.support.jooq.tables.records.WorkspacesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Workspaces extends TableImpl<WorkspacesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.workspaces</code>
     */
    public static final Workspaces WORKSPACES = new Workspaces();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorkspacesRecord> getRecordType() {
        return WorkspacesRecord.class;
    }

    /**
     * The column <code>public.workspaces.id</code>.
     */
    public final TableField<WorkspacesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.workspaces.user_id</code>.
     */
    public final TableField<WorkspacesRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.workspaces.name</code>.
     */
    public final TableField<WorkspacesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.workspaces.description</code>.
     */
    public final TableField<WorkspacesRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.workspaces.created</code>.
     */
    public final TableField<WorkspacesRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.workspaces.deleted</code>.
     */
    public final TableField<WorkspacesRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");

    private Workspaces(Name alias, Table<WorkspacesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Workspaces(Name alias, Table<WorkspacesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.workspaces</code> table reference
     */
    public Workspaces(String alias) {
        this(DSL.name(alias), WORKSPACES);
    }

    /**
     * Create an aliased <code>public.workspaces</code> table reference
     */
    public Workspaces(Name alias) {
        this(alias, WORKSPACES);
    }

    /**
     * Create a <code>public.workspaces</code> table reference
     */
    public Workspaces() {
        this(DSL.name("workspaces"), null);
    }

    public <O extends Record> Workspaces(Table<O> child, ForeignKey<O, WorkspacesRecord> key) {
        super(child, key, WORKSPACES);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.WORKSPACES_USER_IDX);
    }

    @Override
    public UniqueKey<WorkspacesRecord> getPrimaryKey() {
        return Keys.WORKSPACES_PKEY;
    }

    @Override
    public List<UniqueKey<WorkspacesRecord>> getKeys() {
        return Arrays.<UniqueKey<WorkspacesRecord>>asList(Keys.WORKSPACES_PKEY);
    }

    @Override
    public List<ForeignKey<WorkspacesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WorkspacesRecord, ?>>asList(Keys.WORKSPACES__WORKSPACES_USER_ID_FKEY);
    }

    private transient Users _users;

    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.WORKSPACES__WORKSPACES_USER_ID_FKEY);

        return _users;
    }

    @Override
    public Workspaces as(String alias) {
        return new Workspaces(DSL.name(alias), this);
    }

    @Override
    public Workspaces as(Name alias) {
        return new Workspaces(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Workspaces rename(String name) {
        return new Workspaces(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Workspaces rename(Name name) {
        return new Workspaces(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, String, String, LocalDateTime, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
