/*
 * This file is generated by jOOQ.
 */
package net.johanbasson.datavault.support.jooq.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import net.johanbasson.datavault.support.jooq.tables.Workspaces;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkspacesRecord extends UpdatableRecordImpl<WorkspacesRecord> implements Record6<UUID, UUID, String, String, LocalDateTime, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.workspaces.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.workspaces.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.workspaces.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.workspaces.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.workspaces.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.workspaces.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.workspaces.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.workspaces.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.workspaces.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.workspaces.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.workspaces.deleted</code>.
     */
    public void setDeleted(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.workspaces.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, String, String, LocalDateTime, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, UUID, String, String, LocalDateTime, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Workspaces.WORKSPACES.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Workspaces.WORKSPACES.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Workspaces.WORKSPACES.NAME;
    }

    @Override
    public Field<String> field4() {
        return Workspaces.WORKSPACES.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Workspaces.WORKSPACES.CREATED;
    }

    @Override
    public Field<Boolean> field6() {
        return Workspaces.WORKSPACES.DELETED;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public Boolean component6() {
        return getDeleted();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public Boolean value6() {
        return getDeleted();
    }

    @Override
    public WorkspacesRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public WorkspacesRecord value2(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public WorkspacesRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public WorkspacesRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public WorkspacesRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public WorkspacesRecord value6(Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    public WorkspacesRecord values(UUID value1, UUID value2, String value3, String value4, LocalDateTime value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkspacesRecord
     */
    public WorkspacesRecord() {
        super(Workspaces.WORKSPACES);
    }

    /**
     * Create a detached, initialised WorkspacesRecord
     */
    public WorkspacesRecord(UUID id, UUID userId, String name, String description, LocalDateTime created, Boolean deleted) {
        super(Workspaces.WORKSPACES);

        setId(id);
        setUserId(userId);
        setName(name);
        setDescription(description);
        setCreated(created);
        setDeleted(deleted);
    }
}
