/*
 * This file is generated by jOOQ.
 */
package net.johanbasson.datavault.support.jooq;


import net.johanbasson.datavault.support.jooq.tables.Users;
import net.johanbasson.datavault.support.jooq.tables.Workspaces;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USERS_EMAIL_IDX = Internal.createIndex(DSL.name("users_email_idx"), Users.USERS, new OrderField[] { Users.USERS.EMAIL }, true);
    public static final Index WORKSPACES_USER_IDX = Internal.createIndex(DSL.name("workspaces_user_idx"), Workspaces.WORKSPACES, new OrderField[] { Workspaces.WORKSPACES.USER_ID }, false);
}
