/*
 * This file is generated by jOOQ.
 */
package net.johanbasson.datavault.support.jooq;


import net.johanbasson.datavault.support.jooq.tables.Users;
import net.johanbasson.datavault.support.jooq.tables.Workspaces;
import net.johanbasson.datavault.support.jooq.tables.records.UsersRecord;
import net.johanbasson.datavault.support.jooq.tables.records.WorkspacesRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<WorkspacesRecord> WORKSPACES_PKEY = Internal.createUniqueKey(Workspaces.WORKSPACES, DSL.name("workspaces_pkey"), new TableField[] { Workspaces.WORKSPACES.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<WorkspacesRecord, UsersRecord> WORKSPACES__WORKSPACES_USER_ID_FKEY = Internal.createForeignKey(Workspaces.WORKSPACES, DSL.name("workspaces_user_id_fkey"), new TableField[] { Workspaces.WORKSPACES.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
}
