/*
 * This file is generated by jOOQ.
 */
package net.johanbasson.datavault.support.jooq;


import java.util.Arrays;
import java.util.List;

import net.johanbasson.datavault.support.jooq.tables.Users;
import net.johanbasson.datavault.support.jooq.tables.Workspaces;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * The table <code>public.workspaces</code>.
     */
    public final Workspaces WORKSPACES = Workspaces.WORKSPACES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Users.USERS,
            Workspaces.WORKSPACES);
    }
}
