/*
 * This file is generated by jOOQ.
 */
package net.johanbasson.datavault.support.jooq;


import net.johanbasson.datavault.support.jooq.tables.Users;
import net.johanbasson.datavault.support.jooq.tables.Workspaces;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.workspaces</code>.
     */
    public static final Workspaces WORKSPACES = Workspaces.WORKSPACES;
}
